const $=id=>document.getElementById(id);let state={},saveBusy=false;
const statusNames={connecting:'连接中',ready:'已连接',unverified:'已连接',stale:'数据陈旧',expired:'等待重置后刷新',offline:'离线，保留上次快照',unavailable:'额度暂不可用',stopped:'已停止'};
const fmt=n=>Number.isFinite(n)?new Date(n).toLocaleString('zh-CN',{hour12:false}):'未提供';
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n;};
function render(next){state=next;const p=next.settings||{},q=next.quota||{};document.documentElement.style.setProperty('--accent',p.accent||'#9b7cbd');
 if(!saveBusy){for(const key of ['scale','volume','lowThreshold','noticeSeconds','accent'])$(key).value=p[key];for(const key of ['alwaysOnTop','flip','reducedMotion','sound','nativeNotifications'])$(key).checked=!!p[key];}labels();
 $('connection').textContent=`${statusNames[q.status]||'等待连接'} · ${q.account?.masked||'未读取到账户'} · ${q.account?.plan||'订阅未知'}`;
 $('quota-list').replaceChildren();for(const w of q.windows||[]){const card=el('div','quota-item');card.append(el('span','',w.label),el('strong','',Number.isFinite(w.remainingPercent)?`${w.remainingPercent}%`:'—'),el('span','','剩余 · 重置 '+fmt(w.resetsAt)));$('quota-list').append(card);}
 const diagnosticError=q.error?.code==='IDENTITY_UNVERIFIED'?null:q.error?.message;
 $('diagnostic').textContent=`数据源：Codex app-server · 每 60 秒刷新\n最后更新：${fmt(q.observedAt)}${diagnosticError?'\n'+diagnosticError:''}`;
 const mon=next.monitor||{};$('monitor-status').textContent=`监控：${mon.status||'等待事件'} · 当前活动任务 ${next.activeTurns||0}。只统计主会话数字事件，不含子代理。`;
 const box=$('history');box.replaceChildren();for(const row of [...(next.history||[])].reverse()){const d=el('div','history-row');d.append(el('time','',fmt(row.completedAt)),el('strong','',row.title||'任务完成'),el('p','',row.body||''));box.append(d);}if(!box.children.length)box.append(el('div','empty','还没有新的完成记录。启动前的历史通知不会重播。'));drawTrend(next.points||[]);
}
function labels(){for(const [id,format]of [['scale',v=>Math.round(v*100)+'%'],['volume',v=>Math.round(v*100)+'%'],['lowThreshold',v=>v+'% 以下'],['noticeSeconds',v=>v+' 秒']])$(id+'-value').textContent=format(Number($(id).value));}
async function save(){saveBusy=true;labels();const p={};for(const key of ['scale','volume','lowThreshold','noticeSeconds'])p[key]=Number($(key).value);p.accent=$('accent').value;for(const key of ['alwaysOnTop','flip','reducedMotion','sound','nativeNotifications'])p[key]=$(key).checked;await window.dragon.saveSettings(p);saveBusy=false;$('save-state').textContent='设置已保存';}
for(const key of ['scale','volume','lowThreshold','noticeSeconds','accent','alwaysOnTop','flip','reducedMotion','sound','nativeNotifications'])$(key).addEventListener('change',save);
for(const key of ['scale','volume','lowThreshold','noticeSeconds'])$(key).addEventListener('input',labels);
function drawTrend(points){const c=$('trend'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.font='10px Segoe UI';ctx.fillStyle='#b6a7c0';ctx.strokeStyle='#eee7f3';for(const percent of [0,50,100]){const y=12+(100-percent)*.94;ctx.fillText(percent+'%',2,y+3);ctx.beginPath();ctx.moveTo(35,y);ctx.lineTo(w-8,y);ctx.stroke();}if(!points.length){$('trend-note').textContent='读取到真实数据后绘制；未返回的窗口不画为零。';return;}
 const keys=[...new Set(points.flatMap(p=>p.windows.map(w=>w.id)))];const colors=['#9a7bb5','#88aca7','#b39782','#b584a7'];keys.forEach((key,idx)=>{ctx.strokeStyle=colors[idx%colors.length];ctx.lineWidth=2;ctx.beginPath();let prior=null;points.forEach((p,i)=>{const q=p.windows.find(v=>v.id===key);if(!q||!Number.isFinite(q.remainingPercent)){prior=null;return;}const x=36+(points.length>1?i/(points.length-1):0)*(w-47),y=12+(100-q.remainingPercent)*.94;if(!prior||q.resetsAt!==prior.resetsAt)ctx.moveTo(x,y);else ctx.lineTo(x,y);ctx.fillStyle=colors[idx%colors.length];ctx.fillRect(x-1.5,y-1.5,3,3);prior=q;});ctx.stroke();});$('trend-note').textContent=`本次运行 ${points.length} 个观测点 · ${keys.map(k=>points.flatMap(p=>p.windows).find(w=>w.id===k)?.label).join(' / ')} · 重置边界不连线。`;}
$('refresh').onclick=()=>window.dragon.refresh();$('show').onclick=()=>window.dragon.action('show');$('test-notice').onclick=()=>window.dragon.action('test-notice');$('quit').onclick=()=>window.dragon.action('quit');$('clear-history').onclick=()=>{if(confirm('清空本机白龙的完成记录？'))window.dragon.action('clear-history');};
window.dragon.onState(render);window.dragon.getState().then(render);
